import type { Hotel, Room, User } from "./types";

export const seedUsers: User[] = [
  {
    id: "u_admin",
    username: "admin",
    email: "admin@stayhaven.com",
    password: "admin123",
    role: "admin",
    country: "USA",
    city: "New York",
    phone: "+1 555 0100",
    createdAt: new Date().toISOString(),
  },
  {
    id: "u_demo",
    username: "demo",
    email: "demo@stayhaven.com",
    password: "demo123",
    role: "user",
    country: "USA",
    city: "Los Angeles",
    phone: "+1 555 0199",
    createdAt: new Date().toISOString(),
  },
];

export const seedRooms: Room[] = [
  {
    id: "r1",
    hotelId: "h1",
    title: "Ocean View Suite",
    price: 320,
    maxPeople: 2,
    description: "King bed, private balcony, panoramic ocean views.",
    roomNumbers: [
      { number: 101, unavailableDates: [] },
      { number: 102, unavailableDates: [] },
      { number: 103, unavailableDates: [] },
    ],
  },
  {
    id: "r2",
    hotelId: "h1",
    title: "Garden Deluxe",
    price: 220,
    maxPeople: 3,
    description: "Quiet garden-facing room with rainshower bath.",
    roomNumbers: [
      { number: 201, unavailableDates: [] },
      { number: 202, unavailableDates: [] },
    ],
  },
  {
    id: "r3",
    hotelId: "h2",
    title: "Mountain Loft",
    price: 280,
    maxPeople: 4,
    description: "Two-floor loft with mountain panorama and fireplace.",
    roomNumbers: [
      { number: 301, unavailableDates: [] },
      { number: 302, unavailableDates: [] },
    ],
  },
  {
    id: "r4",
    hotelId: "h3",
    title: "City Skyline Studio",
    price: 180,
    maxPeople: 2,
    description: "Modern studio with floor-to-ceiling skyline views.",
    roomNumbers: [
      { number: 401, unavailableDates: [] },
      { number: 402, unavailableDates: [] },
      { number: 403, unavailableDates: [] },
    ],
  },
  {
    id: "r5",
    hotelId: "h4",
    title: "Desert Villa",
    price: 540,
    maxPeople: 6,
    description: "Private pool villa under desert stars.",
    roomNumbers: [
      { number: 1, unavailableDates: [] },
      { number: 2, unavailableDates: [] },
    ],
  },
  {
    id: "r6",
    hotelId: "h5",
    title: "Forest Cabin",
    price: 150,
    maxPeople: 2,
    description: "Cozy cabin nestled in old-growth pines.",
    roomNumbers: [
      { number: 11, unavailableDates: [] },
      { number: 12, unavailableDates: [] },
    ],
  },
];

export const seedHotels: Hotel[] = [
  {
    id: "h1",
    name: "Azure Bay Resort",
    type: "Resort",
    city: "Santorini",
    address: "Caldera Cliff Road, Oia",
    distance: "200m from beach",
    photos: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200",
    ],
    title: "Cliffside escape with infinity pools",
    description:
      "Perched on Santorini's volcanic cliffs, Azure Bay blends whitewashed Cycladic architecture with quiet luxury — sunset views, two infinity pools, and a candlelit cave restaurant.",
    rating: 9.2,
    cheapestPrice: 220,
    featured: true,
    rooms: ["r1", "r2"],
    amenities: ["Infinity pool", "Spa", "Restaurant", "Free WiFi", "Airport shuttle"],
  },
  {
    id: "h2",
    name: "Pinecrest Lodge",
    type: "Lodge",
    city: "Aspen",
    address: "412 Mountain Ridge",
    distance: "1.2km from gondola",
    photos: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
    ],
    title: "Alpine retreat with skiing concierge",
    description:
      "A handcrafted timber lodge on the edge of the woods — fireplace lounges, ski-in/ski-out access, and a rooftop hot tub overlooking the valley.",
    rating: 9.0,
    cheapestPrice: 280,
    featured: true,
    rooms: ["r3"],
    amenities: ["Hot tub", "Fireplace", "Ski storage", "Bar"],
  },
  {
    id: "h3",
    name: "The Meridian",
    type: "Hotel",
    city: "Tokyo",
    address: "2-1-1 Shibuya",
    distance: "300m from Shibuya station",
    photos: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200",
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=1200",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200",
    ],
    title: "Design hotel in the heart of Shibuya",
    description:
      "Floor-to-ceiling windows over Tokyo's neon arteries, a sake bar on the 28th floor, and rooms designed by Kengo Kuma's studio.",
    rating: 8.8,
    cheapestPrice: 180,
    featured: false,
    rooms: ["r4"],
    amenities: ["Sky bar", "Gym", "Concierge"],
  },
  {
    id: "h4",
    name: "Dune Estancia",
    type: "Villa",
    city: "Marrakech",
    address: "Palmeraie 14",
    distance: "20min from Medina",
    photos: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200",
      "https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?w=1200",
      "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=1200",
    ],
    title: "Private villa in the Palmeraie",
    description:
      "Hand-laid tadelakt walls, citrus gardens, and a 25m private pool — a quiet oasis a short drive from the souks.",
    rating: 9.4,
    cheapestPrice: 540,
    featured: true,
    rooms: ["r5"],
    amenities: ["Private pool", "Hammam", "Chef", "Garden"],
  },
  {
    id: "h5",
    name: "Cedar & Stone",
    type: "Cabin",
    city: "Banff",
    address: "Tunnel Mountain Rd",
    distance: "5min from town",
    photos: [
      "https://images.unsplash.com/photo-1518602164578-cd0074062767?w=1200",
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200",
      "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200",
    ],
    title: "Off-grid cabins in the Rockies",
    description:
      "Scandinavian-inspired cabins tucked into old-growth pine — wood stoves, deep soaking tubs, and a private wood-fired sauna.",
    rating: 9.1,
    cheapestPrice: 150,
    featured: false,
    rooms: ["r6"],
    amenities: ["Sauna", "Hiking trails", "Pet friendly"],
  },
  {
    id: "h6",
    name: "Casa del Mar",
    type: "Boutique",
    city: "Lisbon",
    address: "Rua das Flores 42",
    distance: "Old town center",
    photos: [
      "https://images.unsplash.com/photo-1551776235-dde6d482980b?w=1200",
      "https://images.unsplash.com/photo-1587874522487-f9b0e51b86c2?w=1200",
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200",
    ],
    title: "A tile-clad boutique in Alfama",
    description:
      "16th-century townhouse reimagined — azulejo-tiled courtyards, a rooftop with Tagus views, and a tiny natural-wine bar downstairs.",
    rating: 8.9,
    cheapestPrice: 195,
    featured: false,
    rooms: [],
    amenities: ["Rooftop", "Wine bar", "Library"],
  },
];